[package]
name = "js-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.63"
js-sys = "0.3.55"

[dev-dependencies]
wasm-bindgen-test = "0.3"
